name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.0
      - name: Install Hatch
        run: pip install --upgrade hatch
      - name: Run lint
        run: hatch run lint:check
